
// 这个模板生成：GeneratedAssemblyInfo.cs
// 版本映射规则（四段数字满足 AssemblyFileVersion 要求）:
//   Major = yyyy
//   Minor = MMDD (两位月 + 两位日 => 例如 06月23日 -> 0623)
//   Build = HHmm (小时两位 + 分钟两位 => 15:45 -> 1545)
//   Revision = ss (秒 两位)
// <auto-generated />
using System.Reflection;

[assembly: AssemblyFileVersion("2026.0915.1035.17")]
[assembly: AssemblyInformationalVersion("26-09-15 10:35")]
// 下面两个属性会覆盖 AssemblyInfo.cs 中对应的值，
// 因此请在 AssemblyInfo.cs 中注释掉重复定义的 AssemblyProduct / AssemblyCopyright
[assembly: AssemblyProduct("AutoSystem (build: 26-09-15 10:35)")]
[assembly: AssemblyCopyright("Copyright © 2026")]